spring:
  application:
    name: Subscription and Membership management

  datasource:
    url: jdbc:mysql://localhost:3306/subscription?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

  web:
    resources:
      add-mappings: false

  jwt:
    secret: ${JWT_SECRET}
    token-expiration: 604800